Repository MicrosoftDocs/OfficeDocs-Support, pull requests merged in 2021-03, with the labels that each got.

#1139 Update reset-office-365-proplus-activation-state.md
  Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md
Labels: Microsoft submitter

#1146 Updating with latest on Conditional Access status
  Teams/known-issues/tabs-dont-work-after-enabling-conditional-access.md
Labels: Microsoft submitter

#1149 Updating formatting
  SharePoint/SharePointOnline/sharing-and-permissions/access-denied-due-to-org-policies.md
Labels: Microsoft submitter, fixed

#1134 updated new link
  Exchange/ExchangeOnline/email-delivery/cannot-send-mail-mepf.md
Labels: fixed

#1151 Fix Broken URL
  SharePoint/SharePointOnline/sharing-and-permissions/access-denied-due-to-org-policies.md
Labels: Microsoft submitter

#1157 Updates to Known Issues
  Exchange/ExchangeServer/client-connectivity/exchange-security-update-issues.md
  Exchange/ExchangeServer/client-connectivity/media/exchange-security-update-issues/back-end-binding.png
  Exchange/ExchangeServer/client-connectivity/media/exchange-security-update-issues/front-end-binding.png
Labels: Microsoft submitter

#1165 Update fail-to-start-exchange-management-shell-console.md
  Exchange/ExchangeServer/administration/fail-to-start-exchange-management-shell-console.md
Labels: fixed

#1162 Adding 2 new diagnostics and column for article
  SharePoint/SharePointOnline/diagnostics/sharepoint-and-onedrive-diagnostics.md
Labels: Microsoft submitter

#1191 Update send-receive-emails-socketerror.md
  Exchange/ExchangeOnline/email-delivery/send-receive-emails-socketerror.md
Labels: Microsoft submitter

#1172 Added issue on Exchange OAuth Cert being expired
  Exchange/ExchangeServer/client-connectivity/exchange-security-update-issues.md
Labels: Microsoft submitter

#1197 Update authentication-errors-tls12-support.md
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1208 Fix title grammar for Office Add-ins support page
  Office/Client/office-suite-issues/apps-for-office-not-start.md
Labels: Microsoft submitter, fixed

#1224 Remove x86 from ScanEngines download examples
  Exchange/ExchangeServer/setup/manually-update-scan-engines.md
Labels: Microsoft submitter
