Repository MicrosoftDocs/OfficeDocs-Support, pull requests merged in 2021-06, with the labels that each got.

#1514 Update two-onedrive-accounts-when-uploading-attachments.md
  Exchange/ExchangeHybrid/send-emails/two-onedrive-accounts-when-uploading-attachments.md
Labels: Microsoft submitter

#1519 Update troubleshooting-guide-for-sites-stopped-at-provisioning.md
  SharePoint/SharePointOnline/sites/troubleshooting-guide-for-sites-stopped-at-provisioning.md
Labels: freelancer

#1515 Clarifying
  Exchange/ExchangeHybrid/user-and-shared-mailboxes/mailbox-exists-exo-onpremises.md
Labels: freelancer

#1527 Added note
  SharePoint/OneDrive/storage/check-storage-increase-eligibility.md
Labels: Microsoft submitter

#1526 Added note
  SharePoint/OneDrive/sharing-and-permissions/this-item-might-not-exist-error.md
Labels: Microsoft submitter

#1524 Added note
  SharePoint/SharePointOnline/sharing-and-permissions/access-denied-due-to-org-policies.md
Labels: Microsoft submitter

#1525 Added note
  SharePoint/SharePointOnline/sites/compliance-policy-blocking-site-deletion.md
Labels: Microsoft submitter

#1529 Fixed command in dynamic-distribution-group-members-not-receive-emails.md
  Exchange/ExchangeHybrid/groups-and-distribution-lists/dynamic-distribution-group-members-not-receive-emails.md
Labels: freelancer

#1522 Replace M365 network test tool in troubleshoot-migration-issues-in-exchange-hybrid.md
  Exchange/ExchangeOnline/move-or-migrate-mailboxes/troubleshoot-migration-issues-in-exchange-hybrid.md
Labels: freelancer

#1530 Updating owa instructions and images
  Exchange/ExchangeOnline/user-and-shared-mailboxes/how-to-access-other-mailboxes.md
  Exchange/ExchangeOnline/user-and-shared-mailboxes/media/how-to-access-other-mailboxes/add-a-shared-folder.png
  Exchange/ExchangeOnline/user-and-shared-mailboxes/media/how-to-access-other-mailboxes/add-shared-folder.png
  Exchange/ExchangeOnline/user-and-shared-mailboxes/media/how-to-access-other-mailboxes/mailbox-shown-in-owa.png
  Exchange/ExchangeOnline/user-and-shared-mailboxes/media/how-to-access-other-mailboxes/remove-shared-folder.png
Labels: freelancer

#1503 Update fails-starting-excel-mac.md
  Office/Client/excel/fails-starting-excel-mac.md
Labels: freelancer

#1531 update step 8
  Office/Client/word/issues-when-start-or-use-word.md
Labels: freelancer

#1554 Add reference about Win 10
  Microsoft365/admin/access-management/office-feature-disabled.md
Labels: freelancer

#1551 add info about repair procedure in Windows 10
  Outlook/Client/user-interface/custom-mapi-solutions-not-working.md
Labels: freelancer

#1550 Update error-share-break-inheritance.md
  SharePoint/SharePointOnline/lists-and-libraries/error-share-break-inheritance.md
Labels: Microsoft submitter

#1556 Update voicemails-not-delivered.md
  SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md
Labels: Microsoft submitter

#1553 add info about MFA
  Microsoft365/compliance/archive-mailboxes/message-not-moved-to-archive.md
Labels: freelancer

#1541 added note about classic OWA
  Exchange/ExchangeOnline/administration/update-contact-information.md
Labels: freelancer

#1532 Update in Notes section and Notes reformatting
  Office/Client/office-suite-issues/manage-office-program-templates.md
Labels: freelancer

#1533 Update Log file location
  Microsoft365/admin/diagnostic-logs/run-fiddler-trace.md
Labels: freelancer

#1562 Update cannot-disable-facebook-contact-sync-for-organization.md
  Exchange/ExchangeOnline/administration/cannot-disable-facebook-contact-sync-for-organization.md
Labels: Microsoft submitter

#1535 https://github.com/MicrosoftDocs/OfficeDocs-Support/issues/369
  Microsoft365/admin/access-management/set-language-and-region.md
Labels: freelancer

#1540 removed workarounds
  SkypeforBusiness/SkypeServer/server-sign-in/client-not-start-click-meeting-link.md
Labels: freelancer

#1536 Added GPO steps to sign-in-loop.md
  Teams/teams-sign-in/sign-in-loop.md
Labels: freelancer

#1537 Replaced IE by Edge in how-to-join-a-teams-meeting.md
  Teams/meetings/how-to-join-a-teams-meeting.md
Labels: freelancer

#1538 Delete cant-prevent-users-from-changing-profile-picture.md
  Teams/known-issues/cant-prevent-users-from-changing-profile-picture.md
  Teams/toc.yml
Labels: freelancer

#1539 changed license assignment instructions
  Teams/teams-administration/failed-to-auto-discover-domain-error-teams-admin-center.md
Labels: freelancer

#1542 Create takeoutlookonthego.png
  Outlook/Client/Installation/media/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option/takeoutlookonthego.png
  Outlook/Client/installation/how-to-remove-get-and-set-up-outlook-mobile-app-on-my-phone-option.md
Labels: freelancer

#1546 add note about max paper size
  Office/Client/word/operating-parameter-limitation.md
Labels: freelancer

#1547 add note about deleting shape objects also
  Office/Client/excel/vba-writes-to-cells-slowly.md
Labels: freelancer

#1548 Fixing instructions
  SkypeforBusiness/SkypeServer/server-configuration/central-management-store-replication-failures.md
Labels: freelancer

#1552 add info about additional scenario
  Outlook/Client/security/can't-display-dlp-policytip.md
Labels: freelancer

#1555 update notion
  Microsoft365/admin/access-management/set-language-and-region.md
Labels: freelancer

#1561 Update overview-delegation-office-365-hybrid.md
  Exchange/ExchangeHybrid/send-emails/overview-delegation-office-365-hybrid.md
Labels: freelancer

#1564 Removing workaround as is not valid anymore
  SkypeforBusiness/SkypeServer/server-meetings/cant-join-meeting-on-ios-9-2.md
Labels: freelancer

#1566 clarifying tenant
  Teams/teams-sign-in/someone-has-already-setup-teams.md
Labels: freelancer

#1565 Adding info to uccp logs
  SkypeforBusiness/SkypeOnline/online-conferencing/sharing-cannot-connect.md
Labels: freelancer

#1569 Update example
  Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md
Labels: freelancer

#1570 Update force-excel-to-open-new-instance.md
  Office/Client/excel/force-excel-to-open-new-instance.md
Labels: freelancer

#1593 Remove win 12 section
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1591 Update article
  SharePoint/SharePointOnline/diagnostics/sharepoint-and-onedrive-diagnostics.md
Labels: Microsoft submitter

#1578 Update in DMS to decimal degree
  Office/Client/excel/convert-degrees-minutes-seconds-angles.md
Labels: freelancer

#1582 updating to reflect current options
  SharePoint/SharePointOnline/search/search-results-missing.md
Labels: freelancer

#1583 clarifying and improving example
  SharePoint/SharePointOnline/sharing-and-permissions/troubleshoot-error-when-tries-to-access-center.md
Labels: freelancer

#1584 correcting
  SharePoint/SharePointOnline/search/search-results-missing.md
Labels: freelancer

#1599 Update office-365-third-party-network-devices.md
  Microsoft365/admin/miscellaneous/office-365-third-party-network-devices.md
Labels: Microsoft submitter

#1598 Update how-to-enable-office-365-proplus-uls-logging.md
  Office/OfficeExperts/diagnostic-logs/how-to-enable-office-365-proplus-uls-logging.md
Labels: Microsoft submitter

#1592 Update cannot-add-attachment-outlook-web.md
  Exchange/ExchangeServer/mailflow/cannot-add-attachment-outlook-web.md
Labels: freelancer

#1581 Update resolution for 1.2 not enabled.
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1568 update instruction for scenario 1
  Exchange/ExchangeHybrid/user-and-shared-mailboxes/mailbox-exists-exo-onpremises.md
Labels: freelancer

#1589 Update operating-parameter-limitation.md
  Office/Client/word/operating-parameter-limitation.md
Labels: freelancer

#1501 added references to newer versions
  Office/Client/word/issues-when-start-or-use-word.md
Labels: freelancer

#929 Update cant-open-sp-documents-from-chrome.md
  SharePoint/SharePointServer/lists-and-libraries/cant-open-sp-documents-from-chrome.md
Labels: CI created, Microsoft submitter

#1601 changed the GPO to Registry editor
  Outlook/Client/calendaring/room-finder.md
Labels: freelancer

#1602 changed the wording
  Office/Client/visio/open-visio-files-in-visio-web-access.md
Labels: freelancer

#1606 Update account-blocked-error-when-sign-in.md
  Microsoft365/admin/access-management/account-blocked-error-when-sign-in.md
Labels: freelancer

#1612 Removing engines other than Microsoft from Doc
  Exchange/ExchangeServer/setup/manually-update-scan-engines.md
Labels: Microsoft submitter

#1610 Update outlook-error-over-junk-emial-list-limit.md
  Outlook/Client/junk-email/outlook-error-over-junk-emial-list-limit.md
Labels: freelancer

#1613 small rewording
  Teams/teams-administration/include-exclude-teams-from-antivirus-dlp.md
Labels: freelancer

#1615 Update reset-office-365-proplus-activation-state.md
  Office/OfficeExperts/activation/reset-office-365-proplus-activation-state.md
Labels: freelancer

#1617 Added note about SfBO retirement to new-features-in-firmware-update.md
  SkypeforBusiness/SkypeServer/server-phone-system/new-features-in-firmware-update.md
Labels: freelancer

#1618 Added warning note about when you apply a CU to exchange-server-not-display-all-ou.md
  Exchange/ExchangeServer/administration/exchange-server-not-display-all-ou.md
Labels: freelancer

#1619 Update click-to-run-office-on-terminal-server.md
  Office/Client/office-suite-issues/click-to-run-office-on-terminal-server.md
Labels: freelancer

#1620 Update onedrive-for-business-sync-returns-error.md
  SharePoint/OneDrive/sync/onedrive-for-business-sync-returns-error.md
Labels: freelancer

#1622 Changed HDR to UHD in teams-slow-video-meetings-laptops-4k.md
  Teams/known-issues/teams-slow-video-meetings-laptops-4k.md
Labels: freelancer

#1625 Adding useful resource
  Exchange/ExchangeHybrid/calendars/troubleshoot-freebusy-issues-in-exchange-hybrid.md
Labels: freelancer

#1629 Add Hybrid search reference
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1630 Removed incorrect support link for M365
  SharePoint/SharePointOnline/security/handling-ransomware-in-sharepoint-online.md
Labels: Microsoft submitter

#1628 Update sender-rewriting-scheme.md
  Microsoft365/security/antispam/sender-rewriting-scheme.md
Labels: Microsoft submitter

#1635 Added link to EAC steps to pop3-imap-owa-activesync-office-365.md
  Exchange/ExchangeOnline/user-and-shared-mailboxes/pop3-imap-owa-activesync-office-365.md
Labels: freelancer

#1626 add info about changed behavior
  Exchange/ExchangeOnline/send-emails/smtp-submission-improvements.md
Labels: freelancer

#1579 Minor versions - can they be crawled or not?!
  SharePoint/SharePointOnline/search/search-results-missing.md
Labels: Microsoft submitter

#1641 update outlook versions information
  Outlook/Client/message-body/document-inserted-as-icon-with-hyperlink.md
Labels: freelancer

#1639 adjusted formats , added symbols
  Office/Client/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit.md
Labels: freelancer

#1637 update instructions
  Exchange/ExchangeHybrid/email-delivery/on-premises-users-not-getting-emails-from-microsoft-365.md
Labels: freelancer

#1636 minor fix
  Office/Client/office-suite-issues/no-file-previews-file-explorer-switching-to-32-bit.md
Labels: freelancer

#1634 Update how-to-control-autodiscover-via-group-policy.md
  Outlook/Client/profiles-and-accounts/how-to-control-autodiscover-via-group-policy.md
Labels: freelancer

#1633 Update senders-not-receiving-out-of-office-notifications.md
  Exchange/ExchangeOnline/send-emails/senders-not-receiving-out-of-office-notifications.md
Labels: freelancer

#1643 Update hybrid search description to optimize SEO
  SharePoint/SharePointHybrid/search/hybrid-search-failures.md
Labels: Microsoft submitter

#1642 Add a message to Cipher Suite settings order
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1091 Update classic-usage-popularity-reports-discontinued.md
  SharePoint/SharePointOnline/sites/classic-usage-popularity-reports-discontinued.md
Labels: CI created, Microsoft submitter
