Repository MicrosoftDocs/OfficeDocs-Support, pull requests merged in 2021-05, with the labels that each got.

#1341 New diag added
  SharePoint/SharePointOnline/diagnostics/sharepoint-and-onedrive-diagnostics.md
Labels: Microsoft submitter

#1343 Fixing broken links
  SharePoint/SharePointOnline/diagnostics/sharepoint-and-onedrive-diagnostics.md
Labels: Microsoft submitter

#1328 Update virtual-camera-doesnt-work-macos.md
  Teams/teams-on-mac/virtual-camera-doesnt-work-macos.md
Labels: Microsoft submitter

#1317 Update manually-update-scan-engines.md
  Exchange/ExchangeServer/setup/manually-update-scan-engines.md
Labels: Microsoft submitter

#1235 Add Suspend-MailboxDatabaseCopy Workaround Step
  Exchange/ExchangeServer/administration/add-database-copy-seeding-operation-failed.md
Labels: CI created, Microsoft submitter

#1327 Update voicemails-not-delivered.md
  SkypeforBusiness/SkypeHybrid/hybrid-phone-system/voicemails-not-delivered.md
Labels: Microsoft submitter

#1242 Update troubleshoot-meeting-recording-issues.md
  Teams/meetings/troubleshoot-meeting-recording-issues.md
Labels: CI created, Microsoft submitter

#1381 Removing heading as it reads like the entire fix
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1387 Add more information section
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1398 Update references and 7 links
  SharePoint/SharePointOnline/administration/authentication-errors-windows7.md
Labels: Microsoft submitter

#1396 Update error message
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1413 Enable Cipher Suites
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1414 Ciper Suites CMDLet
  SharePoint/SharePointOnline/administration/authentication-errors-windows7.md
Labels: Microsoft submitter

#1411 Update article for mapped drives
  SharePoint/SharePointOnline/administration/troubleshoot-mapped-network-drives.md
Labels: Microsoft submitter

#1406 Update cipher information
  SharePoint/SharePointOnline/administration/authentication-errors-windows7.md
Labels: Microsoft submitter

#1408 Update Windows Server
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1415 Update References
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1405 Add TLS information and protocols check
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1429 Update GPO
  SharePoint/SharePointOnline/administration/authentication-errors-windows7.md
Labels: Microsoft submitter

#1430 Add GPO Note
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1431 Fixing broken Win 7 link
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1114 Update teams-exchange-interaction-issue.md
  Teams/known-issues/teams-exchange-interaction-issue.md
Labels: CI created

#1113 Update presence-not-show-actual-status.md
  Teams/teams-im-presence/presence-not-show-actual-status.md
Labels: CI created

#1153 Update shared-mailboxes-unexpectedly-converted-to-user-mailboxes.md
  Exchange/ExchangeHybrid/user-and-shared-mailboxes/shared-mailboxes-unexpectedly-converted-to-user-mailboxes.md
Labels: CI created

#1440 Update solutions
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1439 Correct solution
  SharePoint/SharePointOnline/administration/authentication-errors-windows7.md
Labels: Microsoft submitter

#992 Add additional changes to address in ndr
  Exchange/ExchangeOnline/email-delivery/imceaex-ndr.md
Labels: CI created

#956 msExchResourceCapacity and msExchResourceDisplay
  Exchange/ExchangeHybrid/calendars/only-can-see-availability-info-of-resource-when-scheduling-meeting.md
Labels: CI created

#1443 Update directory-sync-tool-not-sync-object.md
  Microsoft365/admin/active-directory/directory-sync-tool-not-sync-object.md
Labels: Microsoft submitter

#1459 New diagnostics added
  SharePoint/SharePointOnline/diagnostics/sharepoint-and-onedrive-diagnostics.md
Labels: Microsoft submitter

#1461 Add new error
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1465 Add Cipher order note and delete powershell ref
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1466 Update note
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1471 Remove Win 10 Note
  SharePoint/SharePointOnline/administration/authentication-errors-windows7.md
Labels: Microsoft submitter

#1472 Add note about powershell failure
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1473 Update Powershell note
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1475 Update KB link
  SharePoint/SharePointOnline/administration/authentication-errors-tls12-support.md
Labels: Microsoft submitter

#1476 Update KB
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1477 Update KB
  SharePoint/SharePointOnline/administration/authentication-errors-windows7.md
Labels: Microsoft submitter

#1199 Update object-specified-not-belong-to-list.md
  Teams/files/object-specified-not-belong-to-list.md
Labels: CI created

#1485 Update DHE Ciphers and Server 2012
  SharePoint/OneDrive/administration/error-0x8004de40-in-onedrive.md
Labels: Microsoft submitter

#1495 Update admin-self-help-diagnostics.md
  Teams/teams-administration/admin-self-help-diagnostics.md
Labels: Microsoft submitter

#1491 Changing a PowerShell throttling shortcut
  Exchange/ExchangeOnline/administration/self-help-diagnostics.md
Labels: Microsoft submitter
